name: s3_image_upload
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  connectivity_plus: ^4.0.2
  get: ^4.6.6
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  camera: ^0.10.5+9
  path: ^1.8.3
  intl: ^0.18.1
  permission_handler: ^11.0.1
  image_picker: ^1.0.8
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
